//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMIndonesiaReportsDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryPeriod
    {
        public int FK_CountryID { get; set; }
        public int FK_PeriodID { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public Nullable<int> NumberOfWorkingDays { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Period Period { get; set; }
    }
}
