//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMIndonesiaReportsDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.CountryPeriods = new HashSet<CountryPeriod>();
            this.CustomerSectors = new HashSet<CustomerSector>();
            this.EmployeeRecords = new HashSet<EmployeeRecord>();
            this.GeographicalAreas = new HashSet<GeographicalArea>();
            this.Levels = new HashSet<Level>();
            this.Profiles = new HashSet<Profile>();
            this.SalesTeamTypes = new HashSet<SalesTeamType>();
        }
    
        public int CountryId { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
        public int FK_CurrencyID { get; set; }
        public short MaxLevelsNumber { get; set; }
        public Nullable<long> LastUsedID { get; set; }
        public bool DosageFormLevel { get; set; }
        public bool SupportTendersInSeparateFile { get; set; }
        public bool DailyReportingSupport { get; set; }
        public bool AutomaticSalesUploadSupport { get; set; }
        public string AutomaticSalesUploadResultsEmailAddress { get; set; }
        public Nullable<short> DefaultAutomaticSalesUploadMode { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> FK_AddedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> FK_LastModifiedBy { get; set; }
        public string AdministratorEmailAddress { get; set; }
        public Nullable<int> FK_DefaultStockTypeID { get; set; }
        public string ProcessBICubesJobName { get; set; }
        public bool SupportTendersInSalesFile { get; set; }
        public bool SupportTargetForSalesType { get; set; }
        public Nullable<short> NationalTargetFormat { get; set; }
        public Nullable<short> CustomerTargetingLevelFormat { get; set; }
        public Nullable<short> EmployeeTargetFormat { get; set; }
        public bool EmployeePhasingOverrideParentLevelPhasing { get; set; }
        public bool AllowTargetEntryForProfile { get; set; }
        public string CurrentConfigOLAPLinkedServer { get; set; }
        public string GeographicalOLAPLinkedServer { get; set; }
        public Nullable<bool> SupportTargetSplitting { get; set; }
        public Nullable<bool> ValidateTargetsAgainstParentLevel { get; set; }
        public bool ScoreMappingByJobTitle { get; set; }
        public bool ScoreMappingByIncentiveGroup { get; set; }
        public string FieldForceOLAPLinkedServer { get; set; }
        public Nullable<int> FK_LocalCurrencyID { get; set; }
        public Nullable<bool> IsSupportCurrencyRate { get; set; }
        public Nullable<bool> DeleteExistingInvoices { get; set; }
        public Nullable<bool> SupportNegativeTarget { get; set; }
        public Nullable<bool> EnablePriceSlices { get; set; }
        public Nullable<bool> SupportExpiryDate { get; set; }
        public Nullable<bool> SupportReturnReasonType { get; set; }
        public Nullable<short> CustomerTargetingLevel { get; set; }
        public Nullable<int> FK_PluginID { get; set; }
        public Nullable<bool> PricesPerArea { get; set; }
        public bool CalculateAmountForBonus { get; set; }
        public bool EmployeeTargetPerArea { get; set; }
        public Nullable<short> CalculateTargetAmount { get; set; }
        public Nullable<bool> PricesPerCustomerSectorTargetingGroup { get; set; }
        public Nullable<bool> AutomaticSalesUploadPeriod { get; set; }
        public Nullable<bool> SupportMDMIntegration { get; set; }
        public Nullable<bool> EnableOfftake { get; set; }
        public Nullable<decimal> DistributionFee { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
        public virtual ICollection<CountryPeriod> CountryPeriods { get; set; }
        public virtual ICollection<CustomerSector> CustomerSectors { get; set; }
        public virtual ICollection<EmployeeRecord> EmployeeRecords { get; set; }
        public virtual ICollection<GeographicalArea> GeographicalAreas { get; set; }
        public virtual ICollection<Level> Levels { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<SalesTeamType> SalesTeamTypes { get; set; }
    }
}
