//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMIndonesiaReportsDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSector
    {
        public CustomerSector()
        {
            this.CustomerGroups = new HashSet<CustomerGroup>();
        }
    
        public int CustomerSectorID { get; set; }
        public string CustomerSectorCode { get; set; }
        public string CustomerSectorName { get; set; }
        public int FK_CountryId { get; set; }
        public Nullable<int> FK_CustomerSubTypeID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> FK_AddedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> FK_LastModifiedBy { get; set; }
        public Nullable<int> FK_CustomerSectorTargetingGroupID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<CustomerGroup> CustomerGroups { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
    }
}
