//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMIndonesiaReportsDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBranch
    {
        public CustomerBranch()
        {
            this.ProfileAdditionalAccounts = new HashSet<ProfileAdditionalAccount>();
        }
    
        public long CustomerBranchID { get; set; }
        public long FK_CustomerID { get; set; }
        public string CustomerBranchCode { get; set; }
        public int FK_GeographicalAreaID { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public int FK_CustomerGroupID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> FK_AddedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> FK_LastModifiedBy { get; set; }
        public Nullable<int> FK_FromPeriodID { get; set; }
        public Nullable<int> FK_ToPeriodID { get; set; }
        public bool LoadedFromExternalSystem { get; set; }
        public Nullable<long> FK_IntegrationLogID { get; set; }
        public bool eCard { get; set; }
        public Nullable<int> FK_CustomerCategoryID { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string ContactPerson { get; set; }
        public string TaxRegistrationNumber { get; set; }
        public Nullable<bool> isLocked { get; set; }
        public string IMSCode { get; set; }
        public string PostalCode { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string DistCode1 { get; set; }
        public string DistCode2 { get; set; }
        public string DistCode3 { get; set; }
        public string DistCode4 { get; set; }
    
        public virtual ICollection<ProfileAdditionalAccount> ProfileAdditionalAccounts { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual CustomerGroup CustomerGroup { get; set; }
        public virtual Period Period { get; set; }
        public virtual GeographicalArea GeographicalArea { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
        public virtual Period Period1 { get; set; }
    }
}
