//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMIndonesiaReportsDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerGroup
    {
        public CustomerGroup()
        {
            this.CustomerBranches = new HashSet<CustomerBranch>();
        }
    
        public int CustomerGroupID { get; set; }
        public string CustomerGroupCode { get; set; }
        public string CustomerGroupName { get; set; }
        public string CustomerGroupAbbrLabel { get; set; }
        public int FK_CustomerSectorId { get; set; }
        public short CustomerGroupType { get; set; }
        public string CustomerGroup_SubDis_Alternate_Name { get; set; }
        public Nullable<int> FK_PluginId { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> FK_AddedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> FK_LastModifiedBy { get; set; }
        public Nullable<int> FK_CustomerPlgnID { get; set; }
        public Nullable<bool> PricePerDate { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<short> GracePeriod { get; set; }
        public Nullable<bool> FilesSent { get; set; }
    
        public virtual ICollection<CustomerBranch> CustomerBranches { get; set; }
        public virtual CustomerSector CustomerSector { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
    }
}
