//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMIndonesiaReportsDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRecord
    {
        public EmployeeRecord()
        {
            this.EmployeeLogs = new HashSet<EmployeeLog>();
            this.EmployeeLogs1 = new HashSet<EmployeeLog>();
            this.EmployeeProfiles = new HashSet<EmployeeProfile>();
            this.SystemUsers = new HashSet<SystemUser>();
        }
    
        public long EmployeeID { get; set; }
        public string InsuranceNo { get; set; }
        public string Prefix { get; set; }
        public string EmployeeName { get; set; }
        public string Description { get; set; }
        public int FK_CountryID { get; set; }
        public Nullable<System.DateTime> HiringDate { get; set; }
        public Nullable<System.DateTime> ResignationDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> FK_AddedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> FK_LastModifiedBy { get; set; }
        public string PeopleSoft { get; set; }
        public string NT_Account { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsFieldTrainer { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<EmployeeLog> EmployeeLogs { get; set; }
        public virtual ICollection<EmployeeLog> EmployeeLogs1 { get; set; }
        public virtual ICollection<EmployeeProfile> EmployeeProfiles { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
        public virtual ICollection<SystemUser> SystemUsers { get; set; }
    }
}
