//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMIndonesiaReportsDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLog
    {
        public long EmployeeLogID { get; set; }
        public long FK_EmployeeID { get; set; }
        public Nullable<long> FK_SupervisorID { get; set; }
        public int FK_LevelID { get; set; }
        public bool IsMedicalRep { get; set; }
        public bool VacantRecord { get; set; }
        public string Location { get; set; }
        public bool Marketing { get; set; }
        public int FK_FromPeriodID { get; set; }
        public Nullable<int> FK_ToPeriodID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> FK_AddedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> FK_LastModifiedBy { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual EmployeeRecord EmployeeRecord { get; set; }
        public virtual Period Period { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
        public virtual Level Level { get; set; }
        public virtual EmployeeRecord EmployeeRecord1 { get; set; }
        public virtual Period Period1 { get; set; }
    }
}
