//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMIndonesiaReportsDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeographicalArea
    {
        public GeographicalArea()
        {
            this.CustomerBranches = new HashSet<CustomerBranch>();
            this.ProfileGeographicalAreas = new HashSet<ProfileGeographicalArea>();
            this.GeographicalArea1 = new HashSet<GeographicalArea>();
        }
    
        public int GeographicalAreaID { get; set; }
        public string GeographicalAreaCode { get; set; }
        public string GeographicalAreaName { get; set; }
        public string GeographicalAreaAbbrLabel { get; set; }
        public string Description { get; set; }
        public Nullable<int> FK_ParentID { get; set; }
        public Nullable<int> LevelsNo { get; set; }
        public int FK_CountryID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> FK_AddedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> FK_LastModifiedBy { get; set; }
        public Nullable<int> FK_GeographicalAreaTypeID { get; set; }
        public Nullable<int> FK_SalesTerritoryID { get; set; }
        public Nullable<int> FK_StateTerritoryID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<CustomerBranch> CustomerBranches { get; set; }
        public virtual ICollection<ProfileGeographicalArea> ProfileGeographicalAreas { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual ICollection<GeographicalArea> GeographicalArea1 { get; set; }
        public virtual GeographicalArea GeographicalArea2 { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
    }
}
