//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMIndonesiaReportsDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public Level()
        {
            this.EmployeeLogs = new HashSet<EmployeeLog>();
        }
    
        public int LevelId { get; set; }
        public string LevelCode { get; set; }
        public string LevelName { get; set; }
        public string LevelAbbrLabel { get; set; }
        public bool Visible { get; set; }
        public short Rank { get; set; }
        public int FK_CountryId { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> FK_AddedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> FK_LastModifiedBy { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<EmployeeLog> EmployeeLogs { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
    }
}
