//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMIndonesiaReportsDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Period
    {
        public Period()
        {
            this.CountryPeriods = new HashSet<CountryPeriod>();
            this.CustomerBranches = new HashSet<CustomerBranch>();
            this.CustomerBranches1 = new HashSet<CustomerBranch>();
            this.EmployeeLogs = new HashSet<EmployeeLog>();
            this.EmployeeLogs1 = new HashSet<EmployeeLog>();
            this.EmployeeProfiles = new HashSet<EmployeeProfile>();
            this.EmployeeProfiles1 = new HashSet<EmployeeProfile>();
            this.ProfileAdditionalAccounts = new HashSet<ProfileAdditionalAccount>();
            this.ProfileAdditionalAccounts1 = new HashSet<ProfileAdditionalAccount>();
            this.ProfileGeographicalAreas = new HashSet<ProfileGeographicalArea>();
            this.ProfileGeographicalAreas1 = new HashSet<ProfileGeographicalArea>();
            this.Profiles = new HashSet<Profile>();
            this.Profiles1 = new HashSet<Profile>();
        }
    
        public int PeriodID { get; set; }
        public string PeriodCode { get; set; }
        public string PeriodName { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public int Year { get; set; }
        public Nullable<int> FK_PeriodLYID { get; set; }
    
        public virtual ICollection<CountryPeriod> CountryPeriods { get; set; }
        public virtual ICollection<CustomerBranch> CustomerBranches { get; set; }
        public virtual ICollection<CustomerBranch> CustomerBranches1 { get; set; }
        public virtual ICollection<EmployeeLog> EmployeeLogs { get; set; }
        public virtual ICollection<EmployeeLog> EmployeeLogs1 { get; set; }
        public virtual ICollection<EmployeeProfile> EmployeeProfiles { get; set; }
        public virtual ICollection<EmployeeProfile> EmployeeProfiles1 { get; set; }
        public virtual ICollection<ProfileAdditionalAccount> ProfileAdditionalAccounts { get; set; }
        public virtual ICollection<ProfileAdditionalAccount> ProfileAdditionalAccounts1 { get; set; }
        public virtual ICollection<ProfileGeographicalArea> ProfileGeographicalAreas { get; set; }
        public virtual ICollection<ProfileGeographicalArea> ProfileGeographicalAreas1 { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<Profile> Profiles1 { get; set; }
    }
}
