//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMIndonesiaReportsDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTeam
    {
        public SalesTeam()
        {
            this.Profiles = new HashSet<Profile>();
        }
    
        public long SalesTeamID { get; set; }
        public string SalesTeamCode { get; set; }
        public string SalesTeamName { get; set; }
        public int FK_SalesTeamTypeID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> FK_AddedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> FK_LastModifiedBy { get; set; }
    
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
        public virtual SalesTeamType SalesTeamType { get; set; }
    }
}
