//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMIndonesiaReportsDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTeamType
    {
        public SalesTeamType()
        {
            this.SalesTeams = new HashSet<SalesTeam>();
        }
    
        public int SalesTeamTypeID { get; set; }
        public string SalesTeamTypeName { get; set; }
        public bool OutSourced { get; set; }
        public int FK_CountryId { get; set; }
        public Nullable<int> FK_AddedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> FK_LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<SalesTeam> SalesTeams { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
    }
}
