//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMIndonesiaReportsDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public SystemUser()
        {
            this.Countries = new HashSet<Country>();
            this.Countries1 = new HashSet<Country>();
            this.CustomerBranches = new HashSet<CustomerBranch>();
            this.CustomerBranches1 = new HashSet<CustomerBranch>();
            this.CustomerGroups = new HashSet<CustomerGroup>();
            this.CustomerGroups1 = new HashSet<CustomerGroup>();
            this.CustomerSectors = new HashSet<CustomerSector>();
            this.CustomerSectors1 = new HashSet<CustomerSector>();
            this.EmployeeLogs = new HashSet<EmployeeLog>();
            this.EmployeeLogs1 = new HashSet<EmployeeLog>();
            this.EmployeeProfiles = new HashSet<EmployeeProfile>();
            this.EmployeeProfiles1 = new HashSet<EmployeeProfile>();
            this.EmployeeRecords = new HashSet<EmployeeRecord>();
            this.EmployeeRecords1 = new HashSet<EmployeeRecord>();
            this.GeographicalAreas = new HashSet<GeographicalArea>();
            this.GeographicalAreas1 = new HashSet<GeographicalArea>();
            this.Levels = new HashSet<Level>();
            this.Levels1 = new HashSet<Level>();
            this.Profiles = new HashSet<Profile>();
            this.Profiles1 = new HashSet<Profile>();
            this.ProfileAdditionalAccounts = new HashSet<ProfileAdditionalAccount>();
            this.ProfileAdditionalAccounts1 = new HashSet<ProfileAdditionalAccount>();
            this.ProfileGeographicalAreas = new HashSet<ProfileGeographicalArea>();
            this.ProfileGeographicalAreas1 = new HashSet<ProfileGeographicalArea>();
            this.SalesTeams = new HashSet<SalesTeam>();
            this.SalesTeams1 = new HashSet<SalesTeam>();
            this.SalesTeamTypes = new HashSet<SalesTeamType>();
            this.SalesTeamTypes1 = new HashSet<SalesTeamType>();
            this.SystemUser1 = new HashSet<SystemUser>();
            this.SystemUser11 = new HashSet<SystemUser>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public bool Active { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<int> FK_RoleId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> FK_AddedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> FK_LastModifiedBy { get; set; }
        public Nullable<long> FK_EmployeeID { get; set; }
    
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<Country> Countries1 { get; set; }
        public virtual ICollection<CustomerBranch> CustomerBranches { get; set; }
        public virtual ICollection<CustomerBranch> CustomerBranches1 { get; set; }
        public virtual ICollection<CustomerGroup> CustomerGroups { get; set; }
        public virtual ICollection<CustomerGroup> CustomerGroups1 { get; set; }
        public virtual ICollection<CustomerSector> CustomerSectors { get; set; }
        public virtual ICollection<CustomerSector> CustomerSectors1 { get; set; }
        public virtual ICollection<EmployeeLog> EmployeeLogs { get; set; }
        public virtual ICollection<EmployeeLog> EmployeeLogs1 { get; set; }
        public virtual ICollection<EmployeeProfile> EmployeeProfiles { get; set; }
        public virtual ICollection<EmployeeProfile> EmployeeProfiles1 { get; set; }
        public virtual ICollection<EmployeeRecord> EmployeeRecords { get; set; }
        public virtual ICollection<EmployeeRecord> EmployeeRecords1 { get; set; }
        public virtual EmployeeRecord EmployeeRecord { get; set; }
        public virtual ICollection<GeographicalArea> GeographicalAreas { get; set; }
        public virtual ICollection<GeographicalArea> GeographicalAreas1 { get; set; }
        public virtual ICollection<Level> Levels { get; set; }
        public virtual ICollection<Level> Levels1 { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<Profile> Profiles1 { get; set; }
        public virtual ICollection<ProfileAdditionalAccount> ProfileAdditionalAccounts { get; set; }
        public virtual ICollection<ProfileAdditionalAccount> ProfileAdditionalAccounts1 { get; set; }
        public virtual ICollection<ProfileGeographicalArea> ProfileGeographicalAreas { get; set; }
        public virtual ICollection<ProfileGeographicalArea> ProfileGeographicalAreas1 { get; set; }
        public virtual ICollection<SalesTeam> SalesTeams { get; set; }
        public virtual ICollection<SalesTeam> SalesTeams1 { get; set; }
        public virtual ICollection<SalesTeamType> SalesTeamTypes { get; set; }
        public virtual ICollection<SalesTeamType> SalesTeamTypes1 { get; set; }
        public virtual ICollection<SystemUser> SystemUser1 { get; set; }
        public virtual SystemUser SystemUser2 { get; set; }
        public virtual ICollection<SystemUser> SystemUser11 { get; set; }
        public virtual SystemUser SystemUser3 { get; set; }
    }
}
