//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Account_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Account_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have a premssion to login using Web Application.
        /// </summary>
        internal static string AccessWebPages {
            get {
                return ResourceManager.GetString("AccessWebPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Login.
        /// </summary>
        internal static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Avatar.
        /// </summary>
        internal static string ChangeAvatar {
            get {
                return ResourceManager.GetString("ChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your Password.
        /// </summary>
        internal static string ChangeYourPassword {
            get {
                return ResourceManager.GetString("ChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        internal static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password.
        /// </summary>
        internal static string ConfirmYourPassword {
            get {
                return ResourceManager.GetString("ConfirmYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2002-2015 quTIP. All rights reserved..
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailAddrass {
            get {
                return ResourceManager.GetString("EmailAddrass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address {0} is already in use..
        /// </summary>
        internal static string EmailInUse {
            get {
                return ResourceManager.GetString("EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address entered was not registered..
        /// </summary>
        internal static string EmailNotRegistered {
            get {
                return ResourceManager.GetString("EmailNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been successfully sent with the instructions..
        /// </summary>
        internal static string EmailSuccessful {
            get {
                return ResourceManager.GetString("EmailSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter The Temporary Password..
        /// </summary>
        internal static string EnterTheTemporaryPassword {
            get {
                return ResourceManager.GetString("EnterTheTemporaryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        internal static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading photo.
        /// </summary>
        internal static string ErrorUploadingPhoto {
            get {
                return ResourceManager.GetString("ErrorUploadingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} KB is too big. Maximum file size you can upload is 500 KB..
        /// </summary>
        internal static string FileSizeTooBig {
            get {
                return ResourceManager.GetString("FileSizeTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not an allowed file type. Only jpg, png or gif images can be uploaded..
        /// </summary>
        internal static string FileTypeNotAllowed {
            get {
                return ResourceManager.GetString("FileTypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password ?.
        /// </summary>
        internal static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and get your password reset..
        /// </summary>
        internal static string GetYourPassword {
            get {
                return ResourceManager.GetString("GetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here.
        /// </summary>
        internal static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password can&apos;t be the same old password..
        /// </summary>
        internal static string IncorrectNewPassword {
            get {
                return ResourceManager.GetString("IncorrectNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password. Please login again!.
        /// </summary>
        internal static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data were entered..
        /// </summary>
        internal static string InvalidDataEntered {
            get {
                return ResourceManager.GetString("InvalidDataEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is not a valid email address.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed ,try again..
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Page.
        /// </summary>
        internal static string LoginPage {
            get {
                return ResourceManager.GetString("LoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your account.
        /// </summary>
        internal static string LoginToYourAccount {
            get {
                return ResourceManager.GetString("LoginToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You now have a new password!.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You now have a new profile photo!.
        /// </summary>
        internal static string NewProfilePhoto {
            get {
                return ResourceManager.GetString("NewProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is No Period For Today..
        /// </summary>
        internal static string NoPeriodForToday {
            get {
                return ResourceManager.GetString("NoPeriodForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no worries, click.
        /// </summary>
        internal static string NoWorries {
            get {
                return ResourceManager.GetString("NoWorries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was successfully changed!.
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure the new and the confirmation passwords match.
        /// </summary>
        internal static string PasswordDontMatch {
            get {
                return ResourceManager.GetString("PasswordDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password that is at least 6 characters long.
        /// </summary>
        internal static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirmation do not match..
        /// </summary>
        internal static string PasswordMatchError {
            get {
                return ResourceManager.GetString("PasswordMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Instructions.
        /// </summary>
        internal static string PasswordResetInstructions {
            get {
                return ResourceManager.GetString("PasswordResetInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Info..
        /// </summary>
        internal static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info was saved successfully..
        /// </summary>
        internal static string PersonalInfoSaved {
            get {
                return ResourceManager.GetString("PersonalInfoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try requesting password reset after a few minutes..
        /// </summary>
        internal static string RequestPasswordLater {
            get {
                return ResourceManager.GetString("RequestPasswordLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email to get reset instructions.
        /// </summary>
        internal static string ResetInstructions {
            get {
                return ResourceManager.GetString("ResetInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to reset your password..
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image File to upload a new Profile Image..
        /// </summary>
        internal static string SelectImageFile {
            get {
                return ResourceManager.GetString("SelectImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Password.
        /// </summary>
        internal static string TemporaryPassword {
            get {
                return ResourceManager.GetString("TemporaryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a temporary password already?.
        /// </summary>
        internal static string TemporaryPasswordQ {
            get {
                return ResourceManager.GetString("TemporaryPasswordQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0},
        ///
        ///You can use the following temporary password: &quot;{1}&quot; on the Reset Password page to set your new password.
        ///
        ///Cheers,
        ///IncentiveScorecard Technical Team.
        /// </summary>
        internal static string TempPassword {
            get {
                return ResourceManager.GetString("TempPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your temporary password has expired. You have to get a new one!.
        /// </summary>
        internal static string TempPasswordExpired {
            get {
                return ResourceManager.GetString("TempPasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your temporary password is incorrect..
        /// </summary>
        internal static string TempPasswordIncorrect {
            get {
                return ResourceManager.GetString("TempPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then try it.
        /// </summary>
        internal static string ThenTryIt {
            get {
                return ResourceManager.GetString("ThenTryIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Get Your New Password.
        /// </summary>
        internal static string ToGetYourNewPassword {
            get {
                return ResourceManager.GetString("ToGetYourNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update my Data.
        /// </summary>
        internal static string UpdateMyData {
            get {
                return ResourceManager.GetString("UpdateMyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadPhoto.
        /// </summary>
        internal static string UploadPhoto {
            get {
                return ResourceManager.GetString("UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any username and password..
        /// </summary>
        internal static string UsernameEntry {
            get {
                return ResourceManager.GetString("UsernameEntry", resourceCulture);
            }
        }
    }
}
