//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMIndonesiaReports.App_GlobalResources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global_UI_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global_UI_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global_UI_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-minus-sign.
        /// </summary>
        internal static string ErrorMessageIconClass {
            get {
                return ResourceManager.GetString("ErrorMessageIconClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-info-sign.
        /// </summary>
        internal static string ErrorPortletIconClass {
            get {
                return ResourceManager.GetString("ErrorPortletIconClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-trash.
        /// </summary>
        internal static string IconDelete {
            get {
                return ResourceManager.GetString("IconDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-list-alt.
        /// </summary>
        internal static string IconDetails {
            get {
                return ResourceManager.GetString("IconDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-download.
        /// </summary>
        internal static string IconDownload {
            get {
                return ResourceManager.GetString("IconDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-pencil.
        /// </summary>
        internal static string IconEdit {
            get {
                return ResourceManager.GetString("IconEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-save.
        /// </summary>
        internal static string IconSave {
            get {
                return ResourceManager.GetString("IconSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-undo.
        /// </summary>
        internal static string IconUndo {
            get {
                return ResourceManager.GetString("IconUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-warning-sign.
        /// </summary>
        internal static string IconWarning {
            get {
                return ResourceManager.GetString("IconWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Delete .
        /// </summary>
        internal static string NotDeleted {
            get {
                return ResourceManager.GetString("NotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-ok.
        /// </summary>
        internal static string SuccessIconClass {
            get {
                return ResourceManager.GetString("SuccessIconClass", resourceCulture);
            }
        }
    }
}
