//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMIndonesiaReports.App_GlobalResources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Images {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Images", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Back1.png.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Back.png.
        /// </summary>
        internal static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/img/blank.gif.
        /// </summary>
        internal static string blank {
            get {
                return ResourceManager.GetString("blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/gtk-cancel.png.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/gtk-cancel.png.
        /// </summary>
        internal static string CancelAll {
            get {
                return ResourceManager.GetString("CancelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/CancelSalesOnly.png.
        /// </summary>
        internal static string CancelSalesOnly {
            get {
                return ResourceManager.GetString("CancelSalesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/CancelUpload2.png.
        /// </summary>
        internal static string CancelUpload {
            get {
                return ResourceManager.GetString("CancelUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Clear.png.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/clear.png.
        /// </summary>
        internal static string ClearSearch {
            get {
                return ResourceManager.GetString("ClearSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Copy of successfully.png.
        /// </summary>
        internal static string Commit {
            get {
                return ResourceManager.GetString("Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/commit_noGeoAlloc.png.
        /// </summary>
        internal static string Commit_noGeoAlloc {
            get {
                return ResourceManager.GetString("Commit_noGeoAlloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Copy.png.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/icons_CSV16.png.
        /// </summary>
        internal static string CSV {
            get {
                return ResourceManager.GetString("CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/editdelete.png.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/DeleteSalesOnly.png.
        /// </summary>
        internal static string DeleteSalesOnly {
            get {
                return ResourceManager.GetString("DeleteSalesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/edit.png.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/EndAssignments.png.
        /// </summary>
        internal static string EndAssignments {
            get {
                return ResourceManager.GetString("EndAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/msgerror.png.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/icons_Excel.png.
        /// </summary>
        internal static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/ms-excel.png.
        /// </summary>
        internal static string ExcelML {
            get {
                return ResourceManager.GetString("ExcelML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Execute2.png.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Execute1.png.
        /// </summary>
        internal static string Execute1 {
            get {
                return ResourceManager.GetString("Execute1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/False.png.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/False1.png.
        /// </summary>
        internal static string False1 {
            get {
                return ResourceManager.GetString("False1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Forward1.png.
        /// </summary>
        internal static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/LoadingPnl.gif.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/WebResource.gif.
        /// </summary>
        internal static string LoadingPanel {
            get {
                return ResourceManager.GetString("LoadingPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Merge.png.
        /// </summary>
        internal static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/message.png.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Document-new.png.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/paste.png.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/img/icons_PDF.png.
        /// </summary>
        internal static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/gnome-searchtool.png.
        /// </summary>
        internal static string PerformSearch {
            get {
                return ResourceManager.GetString("PerformSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Update.png.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Refresh.png.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Reject.png.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/execute7.png.
        /// </summary>
        internal static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/edit-undo.png.
        /// </summary>
        internal static string ResetSearchCriteria {
            get {
                return ResourceManager.GetString("ResetSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Review.gif.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Rollback.png.
        /// </summary>
        internal static string Rollback {
            get {
                return ResourceManager.GetString("Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/document-save.png.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/document-save-as.png.
        /// </summary>
        internal static string SaveAndAddNew {
            get {
                return ResourceManager.GetString("SaveAndAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/gnome-searchtool.png.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/ShowAll16.png.
        /// </summary>
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/img/spacer.gif.
        /// </summary>
        internal static string spacer {
            get {
                return ResourceManager.GetString("spacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Submit.png.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/SubmitAll.png.
        /// </summary>
        internal static string SubmitAll {
            get {
                return ResourceManager.GetString("SubmitAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/successfully.png.
        /// </summary>
        internal static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Transfer.png.
        /// </summary>
        internal static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/True.png.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/ok1.png.
        /// </summary>
        internal static string True1 {
            get {
                return ResourceManager.GetString("True1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/ok2.png.
        /// </summary>
        internal static string True2 {
            get {
                return ResourceManager.GetString("True2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/img/icons_PDF.gif.
        /// </summary>
        internal static string TwentyRows {
            get {
                return ResourceManager.GetString("TwentyRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Update.png.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/Upload.png.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/img/loading2.png.
        /// </summary>
        internal static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/warning.png.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/icons/icons_Word16.png.
        /// </summary>
        internal static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
    }
}
