//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pages_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Pages_Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bud And Ach By HCR.
        /// </summary>
        internal static string budAndAchByHCR {
            get {
                return ResourceManager.GetString("budAndAchByHCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Share Report.
        /// </summary>
        internal static string customerShare {
            get {
                return ResourceManager.GetString("customerShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Share Report.
        /// </summary>
        internal static string customersharereport {
            get {
                return ResourceManager.GetString("customersharereport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF Config.
        /// </summary>
        internal static string ffConfig {
            get {
                return ResourceManager.GetString("ffConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance By FF Config.
        /// </summary>
        internal static string ffPerformanceByFFConfig {
            get {
                return ResourceManager.GetString("ffPerformanceByFFConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HCR Performance By Product.
        /// </summary>
        internal static string hcrPerformanceByProduct {
            get {
                return ResourceManager.GetString("hcrPerformanceByProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team To Product.
        /// </summary>
        internal static string teamToProduct {
            get {
                return ResourceManager.GetString("teamToProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory to Brick by Area.
        /// </summary>
        internal static string territoryToBrickByArea {
            get {
                return ResourceManager.GetString("territoryToBrickByArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory to Brick by Brick.
        /// </summary>
        internal static string territorytobrickbybrick {
            get {
                return ResourceManager.GetString("territorytobrickbybrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Details.
        /// </summary>
        internal static string transactiondetails {
            get {
                return ResourceManager.GetString("transactiondetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Summary by Channel .
        /// </summary>
        internal static string transactionsummarybychannel {
            get {
                return ResourceManager.GetString("transactionsummarybychannel", resourceCulture);
            }
        }
    }
}
